### ISSUE TITLE
How to display "About" and "Archives" pages？

### ISSUE THREAD

**Issue by WinPoss** [sonnycalcr/sonnycalcr.github.io#4]
The "About" and "Archives" pages are not displaying correctly.
<img width="412" alt="image" src="https://github.com/user-attachments/assets/cb0a6398-bbb1-40b1-a0df-5b8fad4a6339">

I used a Git repository to deploy a Hugo site. It works fine locally, and both the About and Archives pages are accessible. 
<img width="376" alt="image" src="https://github.com/user-attachments/assets/342ecad8-c6ba-41ac-8848-a94328b1bcf8">

However, when I deploy the public folder to Cloudflare Pages, the navigation links for About and Archives default to the website’s domain instead of the corresponding page links.

I checked the Cloudflare Pages deployment and confirmed that the About and Archives HTML pages are uploaded.

<img width="301" alt="image" src="https://github.com/user-attachments/assets/41a8d5dd-0853-4bf0-9d9d-941b426c4cc1">

And the configuration of the `hugo.yaml` file is as follows:

```
languages:
  en:
    languageName: English
    weight: 1 
    taxonomies: 
      category: categories
      tag: tags
    menus:
      main:
        - name: Home
          pageRef: /
          weight: 5 
        - name: Archives
          pageRef: archives/
          weight: 20
        - name: Categories
          pageRef: categories/
          weight: 25
        - name: About
          pageRef: about/
          weight: 30
```

Is there anything else that needs to be modified?

Thank you.
